import { GREEN_50, GREEN_600 } from '@shared/ui/colors'
import { StyleSheet } from 'react-native'

export const styles = StyleSheet.create({
  historicsContainer: {
    backgroundColor: GREEN_50,
    height: '75%',
    paddingVertical: 0,
    paddingHorizontal: 30,
  },
  navigationHistoricsContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
  },
  helloHistoricsText: {
    fontWeight: 'bold',
    fontSize: 30,
    textAlign: 'center',
    marginTop: 20,
  },
  iconNavigationLeft: {
    marginRight: 150,
  },
  iconNavigationRight: {
    marginLeft: 150,
  },
  titleHistoricsContainer: {
    marginTop: 0,
    marginBottom: 60,
  },
  containerHistoricsContent: {
    width: '100%',
    flexDirection: 'row',
    marginTop: 10,
    marginLeft: 10,
  },
  infoHistoricsDate: {
    width: '25%',
    marginTop: 10,
    marginLeft: 5,
    fontSize: 10,
    textAlign: 'center',
    verticalAlign: 'middle',
    backgroundColor: '#fff',
    borderRadius: 10,
    padding: 10,
    height: '100%',
  },
  infoHistoricsText: {
    width: '55%',
    marginTop: 10,
    marginLeft: 5,
    fontSize: 15,
    textAlign: 'center',
    verticalAlign: 'middle',
    backgroundColor: '#fff',
    borderRadius: 10,
    padding: 10,
    height: '100%',
  },
  viewHistoricsButton: {
    backgroundColor: '#1E90FF',
    marginTop: 10,
    marginLeft: 5,
    padding: 10,
    borderRadius: 10,
    height: '100%',
  },
  viewHistoricsButtonText: {
    marginTop: 10,
  },
  containerHistoricButton: {
    marginTop: 66,
    width: '100%',
    alignItems: 'center',
    paddingBottom: 40,
  },
  historicButton: {
    justifyContent: 'center',
    backgroundColor: GREEN_600,
    padding: 20,
    borderRadius: 20,
    elevation: 10,
    shadowOpacity: 100,
  },
  historicButtonText: {
    color: '#fff',
    verticalAlign: 'middle',
    fontWeight: 'bold',
  },
  historicList: {
    // backgroundColor: '#fff',
    marginLeft: 18,
    marginRight: 18,
  },
  historicIcon: {
    height: 43,
    width: 43,
  },
  historicDate: {
    flexDirection: 'row',
    marginBottom: 5,
  },
  timeContentText: {
    marginVertical: 10,
    color: '#48494a',
    fontSize: 20,
    fontWeight: 'bold',
  },
  viewHistoricContentText: {
    fontSize: 15,
  },
  containerHistoricContent: {
    width: '100%',
    marginTop: 10,
    alignItems: 'center',
    backgroundColor: '#fff',
    borderRadius: 40,
    padding: 10,
    elevation: 3,
    borderWidth: 2,
    borderColor: '#ddd',
  },
  nameContentText: {
    fontSize: 25,
    marginBottom: 10,
    paddingTop: 15,
    fontWeight: 'bold',
    paddingHorizontal: 20,
    paddingVertical: 10,
    color: '#333',
    borderRadius: 5,
  },
  viewHistoricContent: {
    flexDirection: 'column',
    alignItems: 'baseline',
    marginBottom: 3,
    paddingLeft: 15,
  },
})
